AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API for utility functionality on ogbix
Globals:
  Function:
    Runtime: python3.12
    Tracing: Active
Resources:
  Crawlers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: seattle/
      Handler: seattle.handler                          
      MemorySize: 3008
      Timeout: 300
      Policies:  
      - AmazonS3FullAccess
  # Keybuilder:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: london/
  #     Handler: london.handler                          
  #     MemorySize: 3008
  #     Timeout: 300
  #     Policies: 
  #     - AmazonS3ReadOnlyAccess